#!/bin/bash
suiteFile=$1

if [ $# -ne 2 ]; then
  echo "Incorrect number of arguments" 1>&2
  exit 1
fi

for file in `cat ${suiteFile}`; do
  fileIn=`echo "${file}.in"`
  if [ ! -r "${fileIn}" ]; then
    echo "Missing or Unreadable file ${fileIn}" 1>&2
    exit 1
  fi
  fileOut=`echo "${file}.out"`
  if [ ! -r "${fileOut}" ]; then
    echo "Missing or Unreadable file ${fileOut}" 1>&2
    exit 1
  fi
  mktemp /tmp/tempFile.XXXXX > /dev/null
  fileArgs=`echo "${file}.args"`
  if [ ! -r "${fileArgs}" ]; then
    "${2}" < "${fileIn}" > /tmp/tempFile.XXXXX
  else
    "${2}" `cat ${fileArgs}` < "${fileIn}" > /tmp/tempFile.XXXXX
  fi
  diff $fileOut /tmp/tempFile.XXXXX > /dev/null
  if [ ! $? -eq 0 ]; then
    echo "Test failed: ${file}"
    echo "Input:"
    cat "${fileIn}"
    echo "Expected:"
    cat "${fileOut}"
    echo "Actual:"
    cat /tmp/tempFile.XXXXX
  fi
  rm /tmp/tempFile.XXXXX
done
